In [0]:
pip install tensorflow

In [0]:
%tensorflow_version 2.x

In [0]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [0]:
print(tf.version)  # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


**Tensors**


"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

Data Types Include: float32, int32, string and others.

Shape: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

**Creating Tensors**

In [0]:
string = tf.Variable("This in new", tf.string)

In [0]:
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This in new'>

In [0]:
number = tf.Variable(1728, tf.int16)

In [0]:
number

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1728>

In [0]:
floatt = tf.Variable(22.7, tf.float64)

In [0]:
floatt

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=22.7>

**Rank/Degree of Tensors**

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

In [0]:
rank1_tensor = tf.Variable([1,2,3], tf.int16)

In [0]:
rank1_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [0]:
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [0]:
rank2_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes']], dtype=object)>

To determine the rank of a tensor we can call the following method.

In [0]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**Shape of Tensors**

In [0]:
rank1_tensor.shape

TensorShape([3])

In [0]:
rank2_tensor.shape

TensorShape([2, 2])

**Changing Shape**

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

In [0]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

In [0]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


**Types of Tensors**

Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.

Variable

Constant

Placeholder

SparseTensor

With the execption of Variable all these tensors are immuttable, meaning their value may not change during execution.